apiVersion: v1
kind: Pod

metadata:
  name: multi-container-pod

spec:
  containers:
    - name: nginx-container-1
      image: nginx

    - name: centos-container-2
      image: centos
      command: ["/bin/bash"] 
      args: ["-c","sleep 200"]
