apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-emptydir-hostpath
spec:
  volumes:
    - name: hostpath-volume
      hostPath: 			# volume type 'hostPath'
        path: /var/jenkins_home		# Path we are defining in this definition can be local path / NFS paths.
    - name: emptydir-volume             # This is 'emptyDir' volume definition name (Optional), consumer shoule use this name.
      emptyDir: {}                      # This is mandatary String 'emptyDir', if you want to use emptydirectory volues inside containers.

  containers:
    - name: nginx-container-hostpath
      image: nginx
      volumeMounts:
        - name: hostpath-volume
          mountPath: /hostpathMount
        - name: emptydir-volume                 # We are consuming the above defined volume name here. Name Should be same as definition.
          mountPath: /emptydirmount             # Inside a container '/emptydirmount' mount path will get created.
#-----------------------------------------------------#
# 1. Volume type 'hostPath' can be created either by using NFS / local host paths.
# 2. Exiting NFS mounts can be used as 'hostPath' volumes.
# 3. 'hostPath' volumes are NOT 'EPHEMERAL'
# 4. If Pod dies/restarts data will NOT be lost. 
# 5. Since we are using NFS(it should be mounted before creating 'hostPath' volume), if its mounted on all cluster-nodes, same data will be accessible from new Pod.
# 6. If you are using a 'hostPath' as a local path which is NOT available on worker node, it will get cretaed at the time of Pod Creation.
#-----------------------------------------------------#
